find_path(SLEPC_INCLUDE_DIR slepc.h ${SLEPC_PATH} ${SLEPC_PATH}/include NO_DEFAULT_PATH)
find_path(SLEPC_INCLUDE_DIR slepc.h)
find_library(SLEPC_LIBRARY NAMES slepc PATHS ${SLEPC_PATH} ${SLEPC_PATH}/lib ${SLEPC_PATH}/lib64 NO_DEFAULT_PATH)
find_library(SLEPC_LIBRARY NAMES slepc)

if(SLEPC_INCLUDE_DIR AND SLEPC_LIBRARY)
	set(SLEPC_FOUND TRUE)
endif()

if(SLEPC_FOUND)
	if(NOT SLEPC_FIND_QUIETLY)
		message(STATUS "Found SLEPC: ${SLEPC_LIBRARY}")
	endif()
else()
	if(SLEPC_FIND_REQUIRED)
		if(NOT SLEPC_INCLUDE_DIR)
			message(FATAL_ERROR "Could not find SLEPc headers (Add -D SLEPC_PATH=<path> to the cmake commandline for a non-standard installation)")
		endif()
		if(NOT SLEPC_LIBRARY)
			message(FATAL_ERROR "Could not find SLEPc shared libraries (Add -D SLEPC_PATH=<path> to the cmake commandline for a non-standard installation)")
		endif()
	endif()
endif()
