find_path(PETSC_INCLUDE_DIR petsc.h ${PETSC_PATH} ${PETSC_PATH}/include NO_DEFAULT_PATH)
find_path(PETSC_INCLUDE_DIR petsc.h)
find_library(PETSC_LIBRARY NAMES petsc PATHS ${PETSC_PATH} ${PETSC_PATH}/lib ${PETSC_PATH}/lib64 NO_DEFAULT_PATH)
find_library(PETSC_LIBRARY NAMES petsc)

if(PETSC_INCLUDE_DIR AND PETSC_LIBRARY)
	set(PETSC_FOUND TRUE)
endif()

if(PETSC_FOUND)
	if(NOT PETSC_FIND_QUIETLY)
		message(STATUS "Found PETSC: ${PETSC_LIBRARY}")
	endif()
else()
	if(PETSC_FIND_REQUIRED)
		if(NOT PETSC_INCLUDE_DIR)
			message(FATAL_ERROR "Could not find PETSc headers (Add -D PETSC_PATH=<path> to the cmake commandline for a non-standard installation)")
		endif()
		if(NOT PETSC_LIBRARY)
			message(FATAL_ERROR "Could not find PETSc shared libraries (Add -D PETSC_PATH=<path> to the cmake commandline for a non-standard installation)")
		endif()
	endif()
endif()
